### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by thii** [cpisciotta/xcbeautify#17]

**Comment by Cyberbeni** [comment]
I made an action to install any swift tool and add it to path: https://github.com/Cyberbeni/install-swift-tool

Here is an example usage on Linux:
```
jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Swift
      uses: YOCKOW/Action-setup-swift@master
    - name: Install xcbeautify
      uses: Cyberbeni/install-swift-tool@master
      with:
        url: https://github.com/Cyberbeni/xcbeautify
        branch: linux-fixes
    - name: Test
      run: |
        set -o pipefail
        swift test --enable-code-coverage | xcbeautify
```

You can omit the branch parameter and it will build from HEAD
Only tested on Linux but should work with macOS too
Branch parameter can be a tag too
The Install Swift action requires either a swift version input or a `.swift-version` file in your root
